site_name: Poor Pentapod
repo_url: https://github.com/jochenalt/Pentapod-Design
edit_uri: edit/master/docs
repo_name: Poor Pentapod
repo_author: 'Jochen Alt'
site_description: Poor Pentapod 
pages:
    - 'Home': 'index.md'
    - 'Gait': 'gait.md'
    - 'Hardware': 'overview.md'
    - 'Boring Math': 'kinematics.md'
    - 'Construction': 'construction.md'
    - 'Startup Procedure': 'startup-procedure.md'
    - 'Bill Of Material': 'bill-of-material.md'

